INSERT INTO category_rules(pattern, category, priority) VALUES
('REWE', 'Lebensmittel', 10),
('EDEKA', 'Lebensmittel', 10),
('ALDI', 'Lebensmittel', 10),
('LIDL', 'Lebensmittel', 10),
('DM', 'Drogerie', 10),
('ROSSMANN', 'Drogerie', 10),
('SPOTIFY', 'Abos', 10),
('NETFLIX', 'Abos', 10),
('MIETE', 'Miete', 5),
('UBER', 'Transport', 20),
('RESTAURANT', 'Essen gehen', 30),
('BELLA ITALIA', 'Essen gehen', 25),
('FITNESS', 'Sport', 30),
('FITNESSSTUDIO', 'Sport', 25),
('SPARPLAN', 'Sparen/Investieren', 20),
('ETF', 'Sparen/Investieren', 20),
('GEHALT', 'Sonstiges', 40),
('DB ', 'Transport', 20);
